#Configuracoes docker
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# --- Configuracoes local dev ---

# 1. Conexão com o Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/db_brutosBurguer
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.sql-script-encoding=UTF-8

# 2. Configurações do Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Definição do Schema
spring.jpa.properties.hibernate.default_schema=brutos_burguer_dev

# 4. Configuração do Servidor
server.port=8090

# 5. Habilita inserção de dados via arquivos SQL
spring.sql.init.mode=always
